### ISSUE TITLE
docs for pre-commit integration

### ISSUE THREAD

**Issue by zaro0508** [awslabs/git-secrets#189]
It looks like pre-commit framework integration was introduced in PR #116 however there doesn't seem to be any usage docs for it?  I was wondering how would configure a `.pre-commit-config.yaml` file to execute git-secrets?  Also can you pass in options from the .pre-commit-config.yaml file as well?

**Comment by rezabekf** [comment]
The way I set it up is like this: 
```
- repo: https://github.com/awslabs/git-secrets
  rev: b9e96b3212fa06aea65964ff0d5cda84ce935f38
  hooks:
  - id: git-secrets
    entry: git-secrets --scan
    files: .
```

For some weird reason, I can not use tag `1.3.0`, instead i have to use `sha` of the commit (using latest)

**Comment by wchaws** [comment]
Here is my setup
```
repos:
  - repo: https://github.com/awslabs/git-secrets
    rev: 99d01d58ebcc06e237c0e3f3ff5ae628aeef6aa6
    hooks:
      - id: git-secrets
        entry: /usr/bin/env
        args:
          # Using a bash script to ensure aws secrets rules is always installed.
          - bash
          - -c
          - echo "Using aws secrets rules" && git-secrets --register-aws && git-secrets --pre_commit_hook
```
